// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenAIRefactor
{
    internal sealed partial class Vsix
    {
        public const string Id = "OpenAIRefactor.b97b7e88-3406-4f1b-a937-71b9cf457cfb";
        public const string Name = "OpenAIRefactor";
        public const string Description = @"OpenAI Refactor adds to your Edit Menu and allows you to Refactor either the Selected Text, Current Method, or Current Property using your own OpenAI API Key.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Brad Green (Personal)";
        public const string Tags = "";
    }
}
