// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenAIRefactor
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string OpenAIRefactorString = "e85f1c3f-9ccc-40ea-8040-79ac5723910d";
        public static Guid OpenAIRefactor = new Guid(OpenAIRefactorString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int OpenAIRefactorMainMenu = 0x1000;
        public const int MyMenuGroup = 0x1100;
        public const int RefactorCommand = 0x0106;
    }
}