// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenAI_Refactor
{
    internal sealed partial class Vsix
    {
        public const string Id = "OpenAI_Refactor.ecd7b8ea-51cc-4755-8a30-97c3fa46d3e9";
        public const string Name = "OpenAI_Refactor";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Brad Green (Personal)";
        public const string Tags = "";
    }
}
